window.STAMP_DATA =
[
  {
    "id": 1,
    "category": "아름",
    "name": "간절곶등대",
    "nameEn": "Ganjeolgot Lighthouse",
    "gps": "35.3590, 129.3606",
    "address": "울산광역시 울주군 서생면 간절곶1길 39-2",
    "contact": "052-239-6113 (간절곶항로표지관리소)",
    "intro": "한반도의 첫 해가 떠오르는 곳",
    "desc": "한반도에서 가장 먼저 새해를 맞이하는 간절곶, 그 앞바다를 밝히는 간절곶 등대가 있다.",
    "height": "17.0",
    "openDate": "1920.03.26.",
    "manned": "유",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "○ (2001.06.)",
    "region": "울산청"
  },
  {
    "id": 2,
    "category": "아름",
    "name": "독도등대",
    "nameEn": "Dokdo Lighthouse",
    "gps": "37.2393, 131.8698",
    "address": "경상북도 울릉군 울릉읍 독도이사부길 63",
    "contact": "054-791-1161 (독도항로표지관리소)",
    "intro": "동쪽바다 저 멀리 외로운 섬",
    "desc": "대한민국 최동단 화산바위섬에 세워진 등대로 국토 끝단을 밝히고 있는 대한민국 영토주권의 상징이다.",
    "height": "15.0",
    "openDate": "1954.08.10.",
    "manned": "유",
    "heritage": "30호",
    "cultural": "",
    "culturalSpace": "",
    "region": "포항청"
  },
  {
    "id": 3,
    "category": "아름",
    "name": "마라도등대",
    "nameEn": "Marado Lighthouse",
    "gps": "33.1167, 126.2695",
    "address": "제주특별자치도 서귀포시 대정읍 마라로 165",
    "contact": "064-792-8507 (마라도항로표지관리소)",
    "intro": "대한민국 최남단 희망봉 등대",
    "desc": "대한민국 국토의 끝이자 시작인 최남단에 위치한 등대로 동중국해와 제주도 남해안을 운항하는 선박의 길잡이 역할을 하고 있다.",
    "height": "32.0",
    "openDate": "1915.03.15.",
    "manned": "유",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "제주단(부산청)"
  },
  {
    "id": 4,
    "category": "아름",
    "name": "소매물도등대",
    "nameEn": "Somaemuldo Lighthouse",
    "gps": "34.6196, 128.5479",
    "address": "경상남도 통영시 한산면 소매물도길 246",
    "contact": "055-641-0875 (소매물도항로표지관리소)",
    "intro": "닿기 힘들어 더 어여쁜 등대섬",
    "desc": "소매물도의 등대섬은 해안경관이 절경을 이루고 있어 통영 8경 중 으뜸이라 할 수 있다.",
    "height": "13.0",
    "openDate": "1917.08.05.",
    "manned": "유",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "○ (2012.01.)",
    "region": "마산청"
  },
  {
    "id": 5,
    "category": "아름",
    "name": "소청도등대",
    "nameEn": "Socheongdo Lighthouse",
    "gps": "37.7601, 124.7294",
    "address": "인천광역시 옹진군 대청면 소청서로 279",
    "contact": "032-880-6254 (인천지방해양수산청)",
    "intro": "서해 최북단 희망의 길잡이",
    "desc": "서해 최북단 푸른 섬에 위치하여 중국과 인천을 잇는 해상과 휴전선 부근을 지나는 선박의 길잡이 역할을 하고 있다.",
    "height": "18.0",
    "openDate": "1908.01.01.",
    "manned": "유",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "인천청"
  },
  {
    "id": 6,
    "category": "아름",
    "name": "속초등대",
    "nameEn": "Sokcho Lighthouse",
    "gps": "38.2137, 128.6000",
    "address": "강원도 속초시 영금정로5길 8-28",
    "contact": "033-633-3406 (속초항로표지관리소)",
    "intro": "등대 전망대에서 속초를 들여다보다",
    "desc": "설악산과 동해바다를 한눈에 볼 수 있어 속초 8경 중 1경으로 손꼽히고 있으며, 동해안을 운항하는 선박의 길잡이 역할을 하고 있다.",
    "height": "28.0",
    "openDate": "1957.06.08.",
    "manned": "유",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "○ (1999.09.)",
    "region": "동해청"
  },
  {
    "id": 7,
    "category": "아름",
    "name": "어청도등대",
    "nameEn": "Eocheongdo Lighthouse",
    "gps": "36.1250, 125.9678",
    "address": "전라북도 군산시 옥도면 어청도길 240",
    "contact": "063-466-4411 (어청도항로표지관리소)",
    "intro": "망망대해, 등대가 꿈꾸는 맑은 바다",
    "desc": "우리나라 서해안의 남북항로를 통항하는 모든 선박이 이용하는 등대로, 서해안에서 제일 먼저 전파를 이용한 무선표지를 설치·운영했던 등대이다.",
    "height": "12.0",
    "openDate": "1912.03.01.",
    "manned": "유",
    "heritage": "제2호",
    "cultural": "○",
    "culturalSpace": "",
    "region": "군산청"
  },
  {
    "id": 8,
    "category": "아름",
    "name": "영도등대",
    "nameEn": "Youngdo Lighthouse",
    "gps": "35.0523, 129.0921",
    "address": "부산광역시 영도구 전망로 181",
    "contact": "051-405-1201 (영도항로표지관리소)",
    "intro": "바다를 디자인하다, 명승지 안의 명소",
    "desc": "바다만 바라보다 국민의 품으로 돌아온 영도등대는 부산을 대표하는 해양문화공간으로, 우리나라 제1항만을 드나드는 선박의 영원한 길잡이 역할을 하고 있다.",
    "height": "34.0",
    "openDate": "1906.12.01.",
    "manned": "유",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "○ (2004.08.)",
    "region": "부산청"
  },
  {
    "id": 9,
    "category": "아름",
    "name": "오동도등대",
    "nameEn": "Odongdo Lighthouse",
    "gps": "34.7442, 127.7677",
    "address": "전라남도 여수시 오동도로 238-32",
    "contact": "061-662-3999 (오동도항로표지관리소)",
    "intro": "여수의 상징, 오동도 정상에 자리잡은 등대",
    "desc": "충무공 이순신의 호국정신과 역사가 깃든 섬인 오동도 정상에 위치한 오동도등대는 여수항과 광양항 일대를 지나는 수많은 선박을 위해 오늘도 불을 밝히고 있다.",
    "height": "27.0",
    "openDate": "1952.05.12.",
    "manned": "유",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "○ (2011.12.)",
    "region": "부산청"
  },
  {
    "id": 10,
    "category": "아름",
    "name": "옹도등대",
    "nameEn": "Ongdo Lighthouse",
    "gps": "36.6474, 126.0085",
    "address": "충청남도 태안군 근흥면 가의도길 44-59",
    "contact": "041-660-7708(대산지방해양수산청)",
    "intro": "신비의 천혜 절경, 섬이 품은 보물",
    "desc": "태안군의 숨은 보물로, 옹기와 닮아 이름 지어진 옹도에 위치한 등대는 태안 앞 바다를 운항하는 선박의 길잡이 역할을 하고 있다.",
    "height": "25.0",
    "openDate": "1907.01.01.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "대산청"
  },
  {
    "id": 11,
    "category": "아름",
    "name": "우도등대",
    "nameEn": "Udo Lighthouse",
    "gps": "33.4927, 126.9658",
    "address": "제주특별자치도 제주시 우도봉길 105",
    "contact": "064-783-0180 (우도항로표지관리소)",
    "intro": "대한민국 최초의 등대테마공원",
    "desc": "제주 최초로 불을 밝힌 등대로 제주도의 동쪽 끝에 위치하며, 우리나라 최초로 등대를 테마로 하는 등대공원을 조성하여 방문객들에게 볼거리를 제공하고 있다.",
    "height": "16.0",
    "openDate": "1906.03.01.",
    "manned": "유",
    "heritage": "제7호",
    "cultural": "",
    "culturalSpace": "○ (2003.12.)",
    "region": "제주단(부산청)"
  },
  {
    "id": 12,
    "category": "아름",
    "name": "울기등대",
    "nameEn": "Ulgi Lighthouse",
    "gps": "35.4928, 129.4430",
    "address": "울산광역시 동구 등대로 155",
    "contact": "052-251-2125 (울기항로표지관리소)",
    "intro": "동해안의 첫 등대",
    "desc": "울창한 송림이 우거진 울산의 끝에 건립되어 동해안을 운항하는 선박의 이정표 역할을 하고 있다.",
    "height": "24.0",
    "openDate": "1906.03.24.",
    "manned": "유",
    "heritage": "제9호",
    "cultural": "○ (구등탑)",
    "culturalSpace": "○ (2004.12.)",
    "region": "울산청"
  },
  {
    "id": 13,
    "category": "아름",
    "name": "팔미도등대",
    "nameEn": "Palmido Lighthouse",
    "gps": "37.3583, 126.5106",
    "address": "인천광역시 중구 팔미로 28",
    "contact": "032-880-6254 (인천지방해양수산청)",
    "intro": "고단한 세월의 풍파를 견뎌온 최초의 등대",
    "desc": "근대식 건축양식을 대표하는 우리나라 최초의 등대로 그 원형을 보존하기 위해 문화재로 지정하여 관리하고 있으며, 조형미를 갖춘 등대를 신축하여 인천항 이정표 역할을 이어가고 있다.",
    "height": "26.0",
    "openDate": "1903.06.01.",
    "manned": "유",
    "heritage": "제1호",
    "cultural": "○ (사적)",
    "culturalSpace": "○ (2009.01.)",
    "region": "인천청"
  },
  {
    "id": 14,
    "category": "아름",
    "name": "호미곶등대",
    "nameEn": "Homigot Lighthouse",
    "gps": "36.0773, 129.5692",
    "address": "경상북도 포항시 남구 호미곶면 호미곶길 99",
    "contact": "054-284-9814 (호미곶항로표지관리소)",
    "intro": "호랑이의 꼬리에 세운 의지의 등대",
    "desc": "붉은 벽돌로만 건립되어 역사적·문화적 가치가 높아 경상북도 기념물 제39호로 지정되어 있으며, 영일만 주변을 운항하는 선박의 안전을 지켜주고 있다.",
    "height": "26.0",
    "openDate": "1908.12.20.",
    "manned": "유",
    "heritage": "제10호",
    "cultural": "○ (경북 기념물)",
    "culturalSpace": "",
    "region": "포항청"
  },
  {
    "id": 15,
    "category": "아름",
    "name": "홍도등대",
    "nameEn": "Hongdo Lighthouse",
    "gps": "34.7114, 125.2038",
    "address": "전라남도 신안군 흑산면 홍도2길 5",
    "contact": "061-246-3888 (홍도항로표지관리소)",
    "intro": "노을 드리운 천연기념물의 붉은 섬",
    "desc": "서남해안 끝 흑산군도에 위치하여, 해질 무렵 섬 전체가 붉게 보이고, 기암괴석과 노송이 절경을 이루고 있는 홍도는 천연기념물 제170호로 지정된 곳이다.",
    "height": "10.0",
    "openDate": "1931.02.01.",
    "manned": "유",
    "heritage": "제3호",
    "cultural": "",
    "culturalSpace": "",
    "region": "목포청"
  },
  {
    "id": 16,
    "category": "아름",
    "name": "국립등대박물관",
    "nameEn": "National Lighthouse Museum",
    "gps": "36.0780, 129.5679",
    "address": "경상북도 포항시 남구 호미곶면 해맞이로150번길 20",
    "contact": "054-284-4857 (국립등대박물관)",
    "intro": "",
    "desc": "국립등대박물관은 산업기술의 발달과 시대적 변화로 점차 사라져 가는 항로표지시설과 장비들을 영구히 보전, 전시하고 그 역사를 조사·연구하기 위해 1985년 건립되었다.",
    "height": "",
    "openDate": "1985.02.07.",
    "manned": "",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": ""
  },
  {
    "id": 17,
    "category": "역사",
    "name": "가거도등대",
    "nameEn": "Gageodo Lighthouse",
    "gps": "34.0946, 125.0992",
    "address": "전라남도 신안군 흑산면 가거도리 산4",
    "contact": "061-246-5533 (가거도항로표지관리소)",
    "intro": "최서남단의 외딴섬, 자연과 인간의 안식처",
    "desc": "옛 모습을 그대로 간직하고 있는 가거도 \n등대는 서남해안 항해 선박과 동중국해 \n 조업 어선에 희망의 불빛을 선사한다.",
    "height": "7.6",
    "openDate": "1907.12.01.",
    "manned": "유",
    "heritage": "제5호",
    "cultural": "○",
    "culturalSpace": "",
    "region": "목포청"
  },
  {
    "id": 18,
    "category": "역사",
    "name": "가사도등대",
    "nameEn": "Gasado Lighthouse",
    "gps": "34.4604, 126.0427",
    "address": "전라남도 진도군 조도면 가사도리 896-2",
    "contact": "061-542-5600 (가사도항로표지관리소)",
    "intro": "좁고 거친 바닷길과 싸우는 항해자의 길잡이",
    "desc": "목포에서 제주, 부산, 인천을 오가는 \n항로의 교차로에 위치한 가사도등대는 \n배들이 잦은 안개와 빠른 물살을 헤쳐 \n나가는데 도움을 주고 있다.",
    "height": "17.0",
    "openDate": "1915.10.01.",
    "manned": "유",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "목포청(진도소)"
  },
  {
    "id": 19,
    "category": "역사",
    "name": "거문도등대",
    "nameEn": "Geomundo Lighthouse",
    "gps": "34.0072, 127.3222",
    "address": "전라남도 여수시 삼산면 덕촌리 산172-534",
    "contact": "061-666-0906 (거문도항로표지관리소)",
    "intro": "역사의 불빛이 살아 숨쉬는 남해안 최초의 등대",
    "desc": "남해안의 첫 번째 등불인 거문도등대는 \n100년이 넘게 남해 먼바다를 항해하는 \n선박들에 안전한 뱃길을 밝혀주고 있다.",
    "height": "33.0",
    "openDate": "1905.04.10.",
    "manned": "유",
    "heritage": "제17호",
    "cultural": "",
    "culturalSpace": "",
    "region": "여수청"
  },
  {
    "id": 20,
    "category": "역사",
    "name": "당사도등대",
    "nameEn": "Dangsado Lighthouse",
    "gps": "34.0982, 126.6024",
    "address": "전라남도 완도군 소안면 당사리 1",
    "contact": "061-553-8086 (당사도항로표지관리소)",
    "intro": "사연 많은 이름을 가진 항일운동의 시발점",
    "desc": "항일운동이 일어난 역사적 장소인 \n당사도등대는 다양한 이름으로 불리며 \n남해안을 항해하는 배들의 길잡이 \n역할을 하고 있다.",
    "height": "21.0",
    "openDate": "1909.01.01.",
    "manned": "유",
    "heritage": "제21호",
    "cultural": "○",
    "culturalSpace": "",
    "region": "목포청(진도소)"
  },
  {
    "id": 21,
    "category": "역사",
    "name": "말도등대",
    "nameEn": "Maldo Lighthouse",
    "gps": "35.8583, 126.3152",
    "address": "전라북도 군산시 옥도면 말도리 1",
    "contact": "063-441-2314 (군산지방해양수산청)",
    "intro": "고군산군도의 끝 섬, 군산항의 관문",
    "desc": "63개 섬들이 모여 한 폭의 수채화를 그려 \n내는 고군산군도의 끝에 위치한 말도 \n등대는 100년이 넘도록 서해안과 군산 \n항을 오가는 배들의 안전을 지켜주고 \n있다.",
    "height": "26.0",
    "openDate": "1909.11.01.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "군산청"
  },
  {
    "id": 22,
    "category": "역사",
    "name": "목포구등대",
    "nameEn": "Mokpogu Lighthouse",
    "gps": "34.7622, 126.2974",
    "address": "전남 해남군 화원면 매봉길 582",
    "contact": "061-280-1722 (목포지방해양수산청)",
    "intro": "목포항 입구를 밝히는 거대한 범선",
    "desc": "좁고 물살이 거센 목포항 입구를 오가는 \n배들에 지난 100여 년 동안 불빛을 \n비추던 목포구등대는 2003년 범선 \n모양의 새 등대에게 역할을 넘겨주었다.",
    "height": "36.0",
    "openDate": "1908.01.01.",
    "manned": "무",
    "heritage": "제4호",
    "cultural": "○(구등탑)",
    "culturalSpace": "",
    "region": "목포청"
  },
  {
    "id": 23,
    "category": "역사",
    "name": "산지등대",
    "nameEn": "Sanji Lighthouse",
    "gps": "33.5214, 126.5456",
    "address": "제주특별자치도 제주시 건입동 340-2",
    "contact": "064-720-2675 (제주해양수산관리단)",
    "intro": "해넘이 명소이자 제주항의 이정표",
    "desc": "아름다운 일몰을 볼 수 있는 산지등대는 제주항을 드나드는 배들의 안전을 위해 100여 년 동안 불빛을 비추고 있다. 1999년부터는 새 등대가 임무를 이어가고 있으며, 2019년도에는 무인등대로 전환되었다.",
    "height": "18.0",
    "openDate": "1916.10.01.",
    "manned": "무",
    "heritage": "제6호",
    "cultural": "",
    "culturalSpace": "○ (미정)",
    "region": "제주단(부산청)"
  },
  {
    "id": 24,
    "category": "역사",
    "name": "상백도등대",
    "nameEn": "Sangbaekdo Lighthouse",
    "gps": "34.0553, 127.5828",
    "address": "전라남도 여수시 삼산면 거문리 산39",
    "contact": "061-650-6102 (여수지방해양수산청)",
    "intro": "태고의 신비를 간직한 환상의 섬",
    "desc": "명승 제7호로 지정된 아름다운 섬, 백도의 \n기암절벽 위에 세워진 상백도등대는 인근 \n거문도 어장에서 조업하는 어선과 다도 \n해를 항해하는 배들의 안전을 지켜주고 \n있다.",
    "height": "7.8",
    "openDate": "1938.11.01.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "여수청"
  },
  {
    "id": 25,
    "category": "역사",
    "name": "소리도등대",
    "nameEn": "Sorido Lighthouse",
    "gps": "34.4115, 127.8007",
    "address": "전라남도 여수시 남면 연도리 2030-2",
    "contact": "061-650-6102 (여수지방해양수산청)",
    "intro": "남해의 길라잡이, 여수ㆍ광양항의 관문",
    "desc": "금오열도 남쪽 끝 힐링의 섬, 연도에 자리 \n잡은 소리도등대는 지난 100여 년 동안 \n남해안과 여수·광양항을 오가는 배들의 \n길잡이가 되고 있다.",
    "height": "12.0",
    "openDate": "1910.10.04.",
    "manned": "무",
    "heritage": "제22호",
    "cultural": "",
    "culturalSpace": "",
    "region": "여수청"
  },
  {
    "id": 26,
    "category": "역사",
    "name": "암태도등대",
    "nameEn": "Amtaedo Lighthouse",
    "gps": "34.8662, 126.1563",
    "address": "전라남도 신안군 암태면 신석리 산39",
    "contact": "061-280-1722 (목포지방해양수산청)",
    "intro": "복잡한 다도해의 안전 길잡이",
    "desc": "우리나라의 초창기 등대 모습을 그대로 유지하며 등대문화유산 제 27호로 지정된 암태도등대는 오도와 초란도를 항해하는 배들을 위해 100여년 동안 안전길잡이 역할을 하고 있다.",
    "height": "7.0",
    "openDate": "1913.11.",
    "manned": "무",
    "heritage": "제27호",
    "cultural": "",
    "culturalSpace": "",
    "region": "목포청"
  },
  {
    "id": 27,
    "category": "역사",
    "name": "제뢰등대",
    "nameEn": "Jeroe Lighthouse",
    "gps": "35.1077, 129.0674",
    "address": "부산 남구 감만동 626-1",
    "contact": "051-609-6804 (부산지방해양수산청)",
    "intro": "밤바다의 별이 된 부산항의 역사",
    "desc": "등대문화유산 제23호로 지정된 제뢰등대는 1887년 돌을 쌓은 입표로 시작하여 1905년 현재의 콘크리트 등표로 변경되면서 부산항을 오가는 배들의 안전을 지켜주다가 부두 건설 매립공사로 그역 할을 마감하게 되었다.",
    "height": "6.9",
    "openDate": "1905.06.",
    "manned": "무",
    "heritage": "제23호",
    "cultural": "",
    "culturalSpace": "",
    "region": "부산청"
  },
  {
    "id": 28,
    "category": "역사",
    "name": "주문진등대",
    "nameEn": "Jumunjin Lighthouse",
    "gps": "37.8976, 128.8339",
    "address": "강원도 강릉시 주문진읍 주문리 187-2",
    "contact": "033-662-2131 (주문진항로표지관리소)",
    "intro": "강원도 밤바다를 가장 오래 밝혀 온",
    "desc": "건축학적 가치가 높아 등대문화유산 \n제12호로 지정된 주문진등대는 강원도 \n에서 첫 번째로 세워져 동해안을 오가는 \n배들에 희망의 불빛을 비추고 있다.",
    "height": "10.0",
    "openDate": "1918.03.20.",
    "manned": "유",
    "heritage": "제12호",
    "cultural": "",
    "culturalSpace": "",
    "region": "동해청"
  },
  {
    "id": 29,
    "category": "역사",
    "name": "죽변등대",
    "nameEn": "Jukbyeon Lighthouse",
    "gps": "37.0582, 129.4295",
    "address": "경상북도 울진군 죽변면 죽변리 1-23",
    "contact": "054-783-7104 (죽변항로표지관리소)",
    "intro": "군사요충지에 자리 잡은 전설과 역사의 보고",
    "desc": "역사성과 건축학적 가치를 인정받아 \n경상북도 기념물 제154호로 지정된 죽변 \n등대는 수많은 전설을 간직한 채 동해안 \n을 항해하는 선박들의 안전한 길잡이가 \n되고 있다.",
    "height": "16.0",
    "openDate": "1910.11.24.",
    "manned": "유",
    "heritage": "제11호",
    "cultural": "○(경북 기념물)",
    "culturalSpace": "",
    "region": "포항청"
  },
  {
    "id": 30,
    "category": "역사",
    "name": "하조도등대",
    "nameEn": "Hajodo Lighthouse",
    "gps": "34.3110, 126.0877",
    "address": "전라남도 진도군 조도면 창유리 1-2",
    "contact": "061-542-5374 (하조도항로표지관리소)",
    "intro": "남해와 서해를 이어주는 장죽수도의 길잡이",
    "desc": "100년 전의 건축 원형을 유지하고 있는 \n하조도등대는 남해와 서해를 연결하는 \n거친 장죽수도를 항해하는 배들에 든든한 \n길잡이 역할을 하고 있다.",
    "height": "14.0",
    "openDate": "1909.02.01.",
    "manned": "유",
    "heritage": "제29호",
    "cultural": "",
    "culturalSpace": "",
    "region": "목포청(진도소)"
  },
  {
    "id": 31,
    "category": "역사",
    "name": "한산항등표",
    "nameEn": "Hansanhang Beacon",
    "gps": "34.8014, 128.4692",
    "address": "경상남도 통영시 한산면 두억리 산42-33",
    "contact": "055-981-5264 (마산지방해양수산청)",
    "intro": "한산대첩 승전 바다 위의 거북선 등대",
    "desc": "1592년 8월의 한산대첩 승전을 기념하기 \n위해 우리나라 최초로 거북선 디자인을 \n도입하여 암초 위에 세워진 한산항등표 \n는 인근 바다를 오가는 여객선과 어선의 \n안전을 지켜준다.",
    "height": "13.0",
    "openDate": "1963.12.30.",
    "manned": "무",
    "heritage": "제26호",
    "cultural": "",
    "culturalSpace": "",
    "region": "마산청"
  },
  {
    "id": 32,
    "category": "역사",
    "name": "국립울진해양과학관",
    "nameEn": "National Ocean Science Museum",
    "gps": "37.0728, 129.4095",
    "address": "경상북도 울진군 죽변면 해양과학길 8",
    "contact": "054-780-5008(국립해양과학관)",
    "intro": "동해에서 출발하는 세계 바다 탐험",
    "desc": "국립해양과학관은 해양과학을 주제로 한 국내 최초의 국립 교육·체험 전문기관으로. 2020년 한반도에서 독도와 가장 가까운 곳인 죽변에 건립되었다.",
    "height": "",
    "openDate": "2020.07.31.",
    "manned": "",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": ""
  },
  {
    "id": 33,
    "category": "재미",
    "name": "감포항남방파제등대(삼층석탑등대)",
    "nameEn": "Gampohang S.B.Lighthouse",
    "gps": "35.8041, 129.5092",
    "address": "경상북도 경주시 감포읍 감포리 504-50",
    "contact": "054-245-1552 (포항지방해양수산청)",
    "intro": "감은사지 삼층석탑 형태를 양각, 음악으로 형솽화한 등대",
    "desc": "경주에서 가장 큰 어항인 감포항에 설치된 등대로, 야간에는 경관조명이 등탑을 비추고 있어 많은 사람들의 발길이 닿는 아름다운 등대이다.",
    "height": "16.0",
    "openDate": "1935.02.01.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "포항청"
  },
  {
    "id": 34,
    "category": "재미",
    "name": "구시포항남방파제등대(튤립등대)",
    "nameEn": "Gusipohang S.B.Lighthouse",
    "gps": "35.4487, 126.4247",
    "address": "전라북도 고창군 상하면 자룡리 978",
    "contact": "063-441-2314(군산지방해양수산청)",
    "intro": "와인 잔에 핀 꽃잎처럼 노을에 물든 붉은 튤립 등대",
    "desc": "구시포항은 와인 글라스항이라고 불리며,노을이 질 때, 수평선 위로 튤립이 피어나는 신비로움을 간직한 곳이다.",
    "height": "18.9",
    "openDate": "2015.06.24.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "군산청"
  },
  {
    "id": 35,
    "category": "재미",
    "name": "구조라남방파제등대(몽돌등대)",
    "nameEn": "Gujorahang S.B.Lighthouse",
    "gps": "34.8051, 128.7008",
    "address": "경상남도 거제시 일운면 구조라리 191-13",
    "contact": "055-981-5264(마산지방해양수산청)",
    "intro": "등대의 기능을 넘어선 거제 구조라의 랜드마크",
    "desc": "거제시를 대표하고 문화사절 역할을 수행하는 몽돌이와 몽순이 캐릭터를 형상화한 등대로 구조라항의 랜드마크로 자리잡고 있다.",
    "height": "8.85",
    "openDate": "2014.01.24.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "마산청"
  },
  {
    "id": 36,
    "category": "재미",
    "name": "도남항방파제등대(연필등대)",
    "nameEn": "Donamhang E.B.Lighthouse",
    "gps": "34.8295, 128.4370",
    "address": "경상남도 통영시 도남동 도남항방파제 끝",
    "contact": "055-981-5264(마산지방해양수산청)",
    "intro": "통영의 문학과 만난 후세를 밝혀줄 빛줄기",
    "desc": "유치환, 박경리 등 통영이 낳은 문인들의 업적을 기념하기 위해 연필모양을 형상화한 조형등대로 혁신적인 디자인을 접목한 기념비적 등대이다.",
    "height": "17.0",
    "openDate": "1986.12.30.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "마산청"
  },
  {
    "id": 37,
    "category": "재미",
    "name": "목포북항동방파제등대(풍차등대)",
    "nameEn": "Mokpobukhang E.B.Lighthouse",
    "gps": "34.8053, 126.3599",
    "address": "전라남도 목포시 죽교동 672",
    "contact": "061-280-1722(목포지방해양수산청)",
    "intro": "목포여행의 추억을 선사하는 풍차등대",
    "desc": "네덜란드식 풍차 형태의 등대로 호남선의 끝자락에서 목포 앞바다와 신안을 운항하는 선박의 길잡이 역할을 하고 있다.",
    "height": "12.0",
    "openDate": "2009.11.27.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "목포청"
  },
  {
    "id": 38,
    "category": "재미",
    "name": "물치항방파제등대(송이등대)",
    "nameEn": "Mulchihang B.Lighthouse",
    "gps": "38.1534, 128.6121",
    "address": "강원도 양양군 강현면 물치리 7-18",
    "contact": "033-520-6275 (동해지방해양수산청)",
    "intro": "뱃길을 안내하는 송이모양의 귀여운 등대",
    "desc": "강원도 양양의 지역 특산물인 송이버섯을 형상화한 등대로 물치항을 드나드는 어선을 위해 밤마다 불빛을 밝혀주고 있다.",
    "height": "11.0",
    "openDate": "2001.12.07.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "동해청"
  },
  {
    "id": 39,
    "category": "재미",
    "name": "삼길포항방파제등대(우럭등대)",
    "nameEn": "Samgilpohang B.Lighthouse",
    "gps": "37.0069, 126.4519",
    "address": "충청남도 서산시 대산읍 화곡리 1-35",
    "contact": "041-660-7708(대산지방해양수산청)",
    "intro": "바다의 맛과 멋을 느낄 수 있는",
    "desc": "서산 북쪽의 관문 삼길포에서 어선들에게는 안전한 항해 길잡이로, 여행자들에게는 바다쉼터가 되어주는 고마운 등대이다.",
    "height": "15.1",
    "openDate": "2009.01.21.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "대산청"
  },
  {
    "id": 40,
    "category": "재미",
    "name": "서암항남방파제등대(젖병등대)",
    "nameEn": "Seoamhang S.B.Lighthouse",
    "gps": "35.2138, 129.2236",
    "address": "부산광역시 기장군 기장읍 연화리 297-5",
    "contact": "051-609-6804 (부산지방해양수산청)",
    "intro": "저출산 극복을 소망한 젖병 모양의 이색등대",
    "desc": "저출산 문제의 극복과 다산과 풍요라는 희망을 표현하고 2013년 IUSSP 세계인구총회 부산유치를 기원하며 건축된 디자인 등대이다.",
    "height": "3.9",
    "openDate": "2009.09.03.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "부산청"
  },
  {
    "id": 41,
    "category": "재미",
    "name": "선유도항방파제등대(기도등대)",
    "nameEn": "Seonyudohang B.Lighthouse",
    "gps": "35.8270, 126.4183",
    "address": "전라북도 군산시 옥도면 선유도리 474-1",
    "contact": "063-441-2314(군산지방해양수산청)",
    "intro": "소원을 들어주는 기도등대",
    "desc": "고군산군도의 첫 번째 섬인 선유도에 설치되어 선박들의 안전한 항해를 기원하며, 많은 여행객들이 찾아와 꿈과 소원을 비는 기원등대이다.",
    "height": "10.8",
    "openDate": "2008.12.31.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "군산청"
  },
  {
    "id": 42,
    "category": "재미",
    "name": "여수구항방파제등대(하멜등대)",
    "nameEn": "Yeosuguhang B.Hamel Lighthouse",
    "gps": "34.7364, 127.7470",
    "address": "전라남도 여수시 종화동 458-7",
    "contact": "061-650-6102(여수지방해양수산청)",
    "intro": "여수 밤바다를 품은 빞의 향연",
    "desc": "여수구항 해양공원에 자리한 하멜등대는 ‘하멜표류기’로 유명한 네덜란드인 헨드릭 하멜이 여수지역에 머물렀던 것을 기념하기 위해 건립되었다.",
    "height": "10.0",
    "openDate": "2005.01.28.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "여수청"
  },
  {
    "id": 43,
    "category": "재미",
    "name": "완도항방파제등대(꽈배기등대)",
    "nameEn": "Wandohang B.Lighthouse",
    "gps": "34.3256, 126.7531",
    "address": "전라남도 완도군 완도읍 가용리 1017-2",
    "contact": "061-542-9664 (진도항로표지관리소)",
    "intro": "온몸으로 노래하는 꽈배기등대",
    "desc": "국내 최초의 노래하는 등대로 조형 등대 개념을 탈피하고, 터치패드 작동으로 등대와 사람이 상호 작용할 수 있도록 설계되었다.",
    "height": "15.0",
    "openDate": "1989.12.13.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "목포청(진도소)"
  },
  {
    "id": 44,
    "category": "재미",
    "name": "이호랜드방사제등대(조랑말등대)",
    "nameEn": "Iholand G.Lighthouse",
    "gps": "33.5018, 126.4520",
    "address": "제주특별자치도 제주시 이호일동 375-43",
    "contact": "064-720-2675(제주해양수산관리단)",
    "intro": "제주의 상징, 조랑말을 형상화한 등대",
    "desc": "제주도를 상징하는 조랑말은 거친 환경에도 굴하지 않고 지역풍토에 잘 적응하는 지구력 강한 말로서, 거친 바다를 견디며 뱃길을 밝혀주는 등대와 닮았다.",
    "height": "12.0",
    "openDate": "2009.02.04.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "제주단(부산청)"
  },
  {
    "id": 45,
    "category": "재미",
    "name": "정자항북방파제등대(고래등대)",
    "nameEn": "Jeongjahang N.B.Lighthouse",
    "gps": "35.6164, 129.4539",
    "address": "울산광역시 북구 정자동 638",
    "contact": "052-228-5682 (울산지방해양수산청)",
    "intro": "등대가 된 귀신고래",
    "desc": "울산의 상징인 귀신고래가 수면 위로 힘차게 솟구쳐 오르는 모양을 형상화한 등대로 2021년 울산 북구 12경에 선정 되었다.",
    "height": "10.0",
    "openDate": "1991.08.07.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "울산청"
  },
  {
    "id": 46,
    "category": "재미",
    "name": "창포말등대(대게등대)",
    "nameEn": "Changpomal Lighthouse",
    "gps": "36.4255, 129.4346",
    "address": "경상북도 영덕군 영덕읍 창포리 산5-5",
    "contact": "054-245-1552 (포항지방해양수산청)",
    "intro": "영덕대게를 형상화한 동해안 해파랑길 명소",
    "desc": "영덕읍 창포리 끝단인 '창포말'에 세워진 창포말 등대는 영덕의 상징인 대게의 집게발이 24m 높이의 등탑을 감싸고 올라가 태양을 상징하는 붉은색 등롱을 잡으려는 모습으로 디자인된 역동적인 등대이다.",
    "height": "24.4",
    "openDate": "1984.06.24.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "포항청"
  },
  {
    "id": 47,
    "category": "재미",
    "name": "칠암항남방파제등대(야구등대)",
    "nameEn": "Chilamhang S.B.Lighthouse",
    "gps": "35.2995, 129.2627",
    "address": "부산광역시 기장군 일광읍 칠암리 2-15",
    "contact": "051-609-6804 (부산지방해양수산청)",
    "intro": "부산시민의 야구 사랑을 상징",
    "desc": "2008년 베이징 올림픽 야구 경기의 우승을 기념하고 야구 도시로 통칭되는 부산의 야구사랑을 상징하기 위해 건립되었다.",
    "height": "10.0",
    "openDate": "2010.11.30.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "부산청"
  },
  {
    "id": 48,
    "category": "재미",
    "name": "톱머리항방파제등대(비행기등대)",
    "nameEn": "Topmeorihang B.Lighthouse",
    "gps": "34.9663, 126.3901",
    "address": "전라남도 무안군 망운면 피서리 809-33",
    "contact": "061-280-1723(목포지방해양수산청)",
    "intro": "무안 톱머리항 비행기 조형 등대",
    "desc": "인근 무안국제공항의 지역특색을 반영하여 비행기가 이륙하는 모습을 형상화한 등대로 조업선박의 안전항해를 지원하고 있다.",
    "height": "15.0",
    "openDate": "2017.10.26.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "목포청"
  },
  {
    "id": 49,
    "category": "재미",
    "name": "포교항방파제등대(전시관등대)",
    "nameEn": "Pogyohang B.Lighthouse",
    "gps": "34.9060, 128.2728",
    "address": "경상남도 고성군 삼산면 두포리 1085-2",
    "contact": "055-981-5264(마산지방해양수산청)",
    "intro": "어촌의 예술과 휴식이 존재하는 공간",
    "desc": "바다를 가득 담은 포교마을벽화와 마주한 빨간 등대가 일반 등탑의 모양과 달리 건물과 유사한 모양으로 지어져 있다.",
    "height": "8.0",
    "openDate": "2006.12.05.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "마산청"
  },
  {
    "id": 50,
    "category": "재미",
    "name": "국립수산과학관",
    "nameEn": "Fisheries Science Museum",
    "gps": "35.1934, 129.2240",
    "address": "부산광역시 기장군 기장읍 시랑리 408-1",
    "contact": "051-720-3061~6(국립수산과학관)",
    "intro": "미래 자원의 보고, 바다 그 신비의 세계가 열린다.",
    "desc": "해양수산에 관한 과학기술의 발전과정과 미래상을 \n소개하고 바다의 소중함을 알려주는 우리나라 최초 \n해양수산 전문과학관이다.",
    "height": "",
    "openDate": "1997.05.26.",
    "manned": "",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": ""
  },
  {
    "id": 51,
    "category": "풍요",
    "name": "간월도항방파제등대",
    "nameEn": "Ganwoldohang B.Lighthouse",
    "gps": "36.6049, 126.4097",
    "address": "충남 서산시 부석면 간월도리 26-28",
    "contact": "041-660-7708(대산지방해양수산청)",
    "intro": "낙조, 별빛, 조명이 비추는 아름다운 등대",
    "desc": "간월암을 한 눈에 바라볼 수 있는 곳에 위치하여 ,야간에는 화려한 조명이 등대를 비추는 서산의 관광 명소이다",
    "height": "9.5",
    "openDate": "2019.06.14.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "대산청"
  },
  {
    "id": 52,
    "category": "풍요",
    "name": "격포항북방파제등대",
    "nameEn": "Gyeokpohang N.B.Lighthouse",
    "gps": "35.6217, 126.4610",
    "address": "전라북도 부안군 변산면 격포리 794",
    "contact": "063-441-2314(군산지방해양수산청)",
    "intro": "해넘이가 아름다운 등대",
    "desc": "해양수산부에서 선정한 아름다운 어촌 100곳 중 하나인 격포항에 위치한 등대로, 해산물이 풍부하고 해넘이가 아름답다.",
    "height": "10.3",
    "openDate": "1993.12.24.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "군산청"
  },
  {
    "id": 53,
    "category": "풍요",
    "name": "국화도항A호방파제등대",
    "nameEn": "Gukhwadohang B.Lighthouse A",
    "gps": "37.0608, 126.5606",
    "address": "경기도 화성시 우정읍 국화리 136",
    "contact": "031-680-7276(평택지방해양수산청)",
    "intro": "국화꽃이 가득한 섬 국화도에 위치한 등대",
    "desc": "노을이 아름다운 섬 국화도에 위치하며, 국화꽃, 나무들이 즐비하여 풍경이 아름답다.",
    "height": "12.0",
    "openDate": "2005.12.05.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "평택청"
  },
  {
    "id": 54,
    "category": "풍요",
    "name": "궁평항북방파제등대",
    "nameEn": "Gungpyeonghang N.B.Lighthouse",
    "gps": "37.1172, 126.6744",
    "address": "경기도 화성시 서신면 궁평리 692",
    "contact": "031-680-7276(평택지방해양수산청)",
    "intro": "낙조가 아름다운 궁평항에 위치한 등대",
    "desc": "다양한 해양체험을 할 수 있는 궁평항에 위치하여, 제부도, 국화도 등을 운항하는 여객선 및 어선들의 안전한 뱃길을 책임지고 있다.",
    "height": "11.0",
    "openDate": "2016.09.08.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "평택청"
  },
  {
    "id": 55,
    "category": "풍요",
    "name": "남당항방파제등대",
    "nameEn": "Namdanghang B.Lighthouse",
    "gps": "36.5334, 126.4700",
    "address": "충청남도 홍성군 서부면 남당리 862",
    "contact": "041-660-7708(대산지방해양수산청)",
    "intro": "서해 제일의 미항(味港) 남당항을 밝히는 등대",
    "desc": "남당항은 광활하게 펼쳐진 천수만과 어우러진 수산물의 보고로, 대하, 우럭, 새조개, 꽃게, 새우 등 싱싱한 수산물이 있는 홍성의 대표적 관광 명소다.",
    "height": "12.0",
    "openDate": "2011.04.21.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "대산청"
  },
  {
    "id": 56,
    "category": "풍요",
    "name": "대난지도항방파제등대",
    "nameEn": "Daenanjidohang B.Lighthouse",
    "gps": "37.0537, 126.4514",
    "address": "충청남도 당진시 석문면 난지도리 4-26",
    "contact": "041-660-7708(대산지방해양수산청)",
    "intro": "해양의 낭만이 가득한 힐링 등대",
    "desc": "해양레포츠를 즐기기에 최적의 환경을 갖추고 있으며, 가시연꽃, 해당화, 검은머리물떼새 등이 서식하는 생태의 보고에 위치한 등대이다.",
    "height": "9.2",
    "openDate": "2016.06.22.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "대산청"
  },
  {
    "id": 57,
    "category": "풍요",
    "name": "대신등대",
    "nameEn": "Daesin Lighthouse",
    "gps": "35.3528, 126.3874",
    "address": "전라남도 영광군 백수읍 해안로 947-8",
    "contact": "061-280-1722 (목포지방해양수산청)",
    "intro": "석양이 아름다운 영광 백수해안도로에 우뚝 선",
    "desc": "노을 전시관을 옆에 두고 있을 만큼 낙조가 아름다워 낭만적인 노을과 빼어난 자연경관을 담을 수 있는 해넘이 명소로 유명하다.",
    "height": "16.4",
    "openDate": "2013.07.05.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "목포청"
  },
  {
    "id": 58,
    "category": "풍요",
    "name": "마량진항남방파제등대",
    "nameEn": "Maryangjinhang S.B.Lighthouse",
    "gps": "36.1295, 126.5087",
    "address": "충청남도 서천군 서면 마량리 339-8",
    "contact": "041-660-7708(대산지방해양수산청)",
    "intro": "서해안 낙조와 일출을 모두 감상할 수 있는",
    "desc": "마량진항은 지형적 특성으로 인해 서해안 낙조와 일출을 모두 감상할 수 있는 곳이다.",
    "height": "9.0",
    "openDate": "2007.06.01.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "대산청"
  },
  {
    "id": 59,
    "category": "풍요",
    "name": "무창포항방파제등대",
    "nameEn": "Muchangpohang B.Lighthouse",
    "gps": "36.2498, 126.5352",
    "address": "충청남도 보령시 웅천읍 관당리 888-58",
    "contact": "041-660-7708(대산지방해양수산청)",
    "intro": "신비의 바닷길 모세의 기적이 있는 등대",
    "desc": "보령8경 중 하나인 신비의 바닷길과 아름다운 낙조로 유명한 무창포에 있으며, 노을이 내리는 항구의 아름다움을 간직한 등대이다.",
    "height": "11.0",
    "openDate": "1991.11.29.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "대산청"
  },
  {
    "id": 60,
    "category": "풍요",
    "name": "연평도등대",
    "nameEn": "Yeonpyeongdo Lighthouse",
    "gps": "37.6535, 125.6864",
    "address": "인천광역시 옹진군 연평면 연평로 682번길 62",
    "contact": "032-880-6254 (인천지방해양수산청)",
    "intro": "평화의 바다를 비추는 등대",
    "desc": "군사 보안 문제로 1974년 가동을 중단한 인천 연평도 등대는 45년만에 다시 불을 밝혔다. 연평도등대 도달거리는 20마일(약32km) 일몰에서 일출때 까지 비춘다",
    "height": "9.5",
    "openDate": "1960.03.23.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "인천청"
  },
  {
    "id": 61,
    "category": "풍요",
    "name": "용기포항서방파제등대",
    "nameEn": "Yonggipohang W.B.Lighthouse",
    "gps": "37.9541, 124.7383",
    "address": "인천광역시 옹진군 백령면 진촌리 2621",
    "contact": "032-880-6254 (인천지방해양수산청)",
    "intro": "대한민국 최북단 섬 백령도에 세워진",
    "desc": "백령도의 서쪽에 위치한 용기포항 주변에는 심청전의 효심을 알리기 위해 건립된 심청각과 서해의 해금강이라 불리는 규암 절벽 두무진 등이 위치해 있어 많은 볼거리를 자랑한다.",
    "height": "9.0",
    "openDate": "2011.11.02.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "인천청"
  },
  {
    "id": 62,
    "category": "풍요",
    "name": "인천항역무선방파제등대",
    "nameEn": "Incheonhang Yeokmuseon B.Lighthouse",
    "gps": "37.4544, 126.5912",
    "address": "인천광역시 중구 항동7가 82-11",
    "contact": "032-880-6254 (인천지방해양수산청)",
    "intro": "등대의 우아한 곡선과 곧은 직선의 아름다운 조화",
    "desc": "수직으로 뻗은 기존의 등대와는 달리 우아한 곡선의 형태를 지닌 등대이다. 등대 앞에 해룡이와 해린이 캐릭터가 자리잡아 수호신처럼 등대를 지킨다",
    "height": "14.0",
    "openDate": "1998.02.20.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "인천청"
  },
  {
    "id": 63,
    "category": "풍요",
    "name": "입파도등대",
    "nameEn": "Ippado Lighthouse",
    "gps": "37.1087, 126.5396",
    "address": "경기도 화성시 우정읍 국화리 산4-1",
    "contact": "031-680-7276(평택지방해양수산청)",
    "intro": "태고의 신비를 묻고 우뚝 솟아 있는 붉은 기암괴석 위",
    "desc": "평택지방해양수산청이 선정한 '일몰이 아름다운 서해안 등대 6곳' 중 하나로, 산 정상에 위치한 등대에서 서해안의 아름다운 풍경을 한 눈에 볼 수 있다.",
    "height": "26.0",
    "openDate": "2007.12.14.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "평택청"
  },
  {
    "id": 64,
    "category": "풍요",
    "name": "제부도항방파제등대",
    "nameEn": "jebudohang B.Lighthouse",
    "gps": "37.1794, 126.6221",
    "address": "경기도 화성시 서신면 제부리 289-14",
    "contact": "031-680-7276(평택지방해양수산청)",
    "intro": "하루 두 번 모세의 기적이 펼쳐지는 제부도에 위치한 빨간 등대",
    "desc": "해양레저를 즐길 수 있는 제부마리나항에 위치한 등대로, 바다와 연결된 전망데크에서 서해바다의 아름다운 풍경을 조망할 수 있다.",
    "height": "9.3",
    "openDate": "2007.10.25.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "평택청"
  },
  {
    "id": 65,
    "category": "풍요",
    "name": "홍원항마리나방파제등대",
    "nameEn": "Hongwonhang Marina B.Lighthouse",
    "gps": "36.1610, 126.5064",
    "address": "충청남도 서천군 서면 도둔리 1469",
    "contact": "041-660-7708(대산지방해양수산청)",
    "intro": "서천의 미항 홍원항에 위치한",
    "desc": "홍원항은 춘장대해수욕장과 동백정이 있는 언덕사이의 움푹한 만에 있는 항구로 방파제 끝에 위치한 등대에서 잔잔한 서해바다를 바라볼 수 있는 낭만의 여행지 이다.",
    "height": "13.7",
    "openDate": "2010.01.18.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "대산청"
  },
  {
    "id": 66,
    "category": "풍요",
    "name": "흑산도항방파제등대",
    "nameEn": "Heuksandohang B.Lighthouse",
    "gps": "34.6887, 125.4381",
    "address": "전라남도 신안군 흑산면 예리 166-9",
    "contact": "061-280-1722 (목포지방해양수산청)",
    "intro": "천사 날개와 선박을 형상화한 천사등대",
    "desc": "천사의 섬 신안을 모티브로 2013년 개량된 흑산도항방파제등대는 등탑 주변에 설치된 LED조명으로 인해 이국적인 야간 경관을 자랑한다.",
    "height": "13.0",
    "openDate": "1970.05.24.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "목포청"
  },
  {
    "id": 67,
    "category": "풍요",
    "name": "국립해양생물자원관",
    "nameEn": "National Marine Biodiversity Institute of Korea",
    "gps": "36.0179, 126.6701",
    "address": "충남 서천군 장항읍 장산로101번길 75",
    "contact": "041-950-0694(국립해양생물자원관)",
    "intro": "새로운 미래를 열어갈 해양생명자원 가치창조의 산실",
    "desc": "해양생물 주권확보를 위한 해양바이오 글로벌 연구기관으로서 해양생명자원 가치 창출로 해양경제 발전과 국민행복 실현을 목표로 하며,국내 유일의 해양생물 전문 박물관인 씨큐리움을 운영하고 있다.",
    "height": "",
    "openDate": "2015.04.20.",
    "manned": "",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": ""
  },
  {
    "id": 68,
    "category": "힐링",
    "name": "녹산곶등대",
    "nameEn": "Noksangot Lighthouse",
    "gps": "34.062861, 127.292639",
    "address": "전남 여수시 삼산면 서도리 산 233-1",
    "contact": "061-650-6102 (여수지방해양수산청)",
    "intro": "",
    "desc": "녹산도의 아름다움을 간직한 등대\n거문도의 뱃노래길을 따라 녹산등대에 가다보면 \n거문도가 한눈에 보이는 녹문정과 인어해양 \n공원을 차례로 만날 수 있으며, 등대에서 \n바라보는 해안 절벽과 서도마을 길은 절경이다.",
    "height": "15.0",
    "openDate": "1958.01.31.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "여수청"
  },
  {
    "id": 69,
    "category": "힐링",
    "name": "돌산항남방파제등대",
    "nameEn": "Dolsanhang S.B.Lighthouse",
    "gps": "34.612444, 127.722139",
    "address": "전남 여수시 돌산읍 군내리 1581",
    "contact": "061-650-6102 (여수지방해양수산청)",
    "intro": "",
    "desc": "1971년 국가어항으로 지정된 돌산항에서 \n주변도서를 오가는 선박들의 안전한 길잡이가 \n되는 등대로 갓 잡은 활어를 판매하는 \n활어 위판장으로 유명한 항구이다.",
    "height": "14.0",
    "openDate": "2021.12.31.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "여수청"
  },
  {
    "id": 70,
    "category": "힐링",
    "name": "마량항중방파제등대",
    "nameEn": "Maryanghang M.B.Lighthouse",
    "gps": "34.446667, 126.818556",
    "address": "전남 강진군 미항로 154",
    "contact": "061-542-9664 (진도항로표지관리소)",
    "intro": "",
    "desc": "강진만의 끝자락에 있는 마량항은 \n주변 풍경이 수려해\n마량미항이라고도 부른다.",
    "height": "8.6",
    "openDate": "1994.01.06.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "목포청(진도소)"
  },
  {
    "id": 71,
    "category": "힐링",
    "name": "마산항서파제제서단등대",
    "nameEn": "Masanhang W.B.Lighthouse",
    "gps": "35.199278, 128.578250",
    "address": "경남 창원시 마산합포구 수산1길 240",
    "contact": "055-981-5264(마산지방해양수산청)",
    "intro": "",
    "desc": "마산항서파제제의 동·서단에 ‘고향’ 이미지를 \n투영해 집 모양으로 만들어진 방파제 등대로 \n등대에 직접 올라가 마산만 전경을 \n바라볼 수 있다.",
    "height": "10.3",
    "openDate": "1992.11.17.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "마산청"
  },
  {
    "id": 72,
    "category": "힐링",
    "name": "방두포등대",
    "nameEn": "Bangdoopo Lighthouse",
    "gps": "33.4274167, 126.9336389",
    "address": "제주특별자치도 서귀포시 성산읍 고성리 47",
    "contact": "064-720-2675 (제주해양수산관리단)",
    "intro": "",
    "desc": "지역민들은 출어할 때는 등대를 보며 \n풍어를 기원하고, 귀항할 때는 가정의 \n평안을 빌어와 소원등대로 불리고 있다.",
    "height": "7.0",
    "openDate": "1980.03.23.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "제주단(부산청)"
  },
  {
    "id": 73,
    "category": "힐링",
    "name": "백야도등대",
    "nameEn": "Baegyado Lighthouse",
    "gps": "34.609083, 127.654306",
    "address": "전남 여수시 화정면 백야등대길 48",
    "contact": "061-650-6102 (여수지방해양수산청)",
    "intro": "",
    "desc": "여수와 나로도를 오고 가는 \n남해 중부 연안항로를 운항하는 \n선박의 안전을 지켜오고 있다.",
    "height": "24.0",
    "openDate": "1928.12.10.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "여수청"
  },
  {
    "id": 74,
    "category": "힐링",
    "name": "삼천포구항동방파제등대",
    "nameEn": "Samcheonpoguhang E.B.Lighthouse",
    "gps": "34.923222, 128.067167",
    "address": "경남 사천시 등대길 67",
    "contact": "055-981-5264(마산지방해양수산청)",
    "intro": "",
    "desc": "우리나라 최대의 어업중심지에서 \n수많은 조업 선박의 안전운항을 위하여 \n불빛을 밝히고 있다.",
    "height": "8.2",
    "openDate": "1998.12.15.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "마산청"
  },
  {
    "id": 75,
    "category": "힐링",
    "name": "서이말등대",
    "nameEn": "Seoimal Lighthouse",
    "gps": "34.787722, 128.738333",
    "address": "경상남도 거제시 일운면 서이말길 478",
    "contact": "055-681-1607 (서이말항로표지관리소)",
    "intro": "",
    "desc": "거제 동남부 끝단에 위치하여 \n인근을 통항하는 선박의 \n주요 지표 역할을 수행하고 있다.",
    "height": "15.2",
    "openDate": "1944.01.15.",
    "manned": "유",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "마산청"
  },
  {
    "id": 76,
    "category": "힐링",
    "name": "술상항남방파제등대",
    "nameEn": "Sulsanghang S.B.Lighthouse",
    "gps": "34.989278, 127.923500",
    "address": "경남 하동군 진교면 술상리 741-2번지",
    "contact": "055-981-5264(마산지방해양수산청)",
    "intro": "",
    "desc": "등대가 지키고 있는 곳은 \n남강과 남해가 만나는 곳으로 \n한려해상 국립공원에 속해있다.",
    "height": "13.0",
    "openDate": "2017.12.26.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "마산청"
  },
  {
    "id": 77,
    "category": "힐링",
    "name": "신창등대",
    "nameEn": "Sinchang Lighthouse",
    "gps": "33.345528, 126.169444",
    "address": "제주특별자치도 제주시 한경면 신창리 1481-14",
    "contact": "064-720-2675 (제주해양수산관리단)",
    "intro": "",
    "desc": "등대 주변으로 풍력발전기들이 \n줄지어 늘어서 있어 이 일대를 \n신창리 풍차해안길이라 부른다.",
    "height": "11.0",
    "openDate": "1965.05.25.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "제주단(부산청)"
  },
  {
    "id": 78,
    "category": "힐링",
    "name": "애도등대",
    "nameEn": "Aedo Lighthouse",
    "gps": "34.465806, 127.442639",
    "address": "전남 고흥군 봉래면 사양리 563",
    "contact": "061-650-6102 (여수지방해양수산청)",
    "intro": "",
    "desc": "쑥이 많아 쑥섬이라 불렸으며 \n같은 뜻의 한자로 애도라 한다. \n애도 내에서는 성화등대로도 불린다.",
    "height": "13.0",
    "openDate": "2007.11.22.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "여수청"
  },
  {
    "id": 79,
    "category": "힐링",
    "name": "죽도등대",
    "nameEn": "Jukdo Lighthouse",
    "gps": "33.311500, 126.146167",
    "address": "제주특별자치도 제주시 한경면 고산리 산117 (산 정상)",
    "contact": "064-720-2675 (제주해양수산관리단)",
    "intro": "",
    "desc": "제주도에 딸린 무인도 가운데 \n가장 큰 차귀도에 있는 등대로 \n섬 전체가 국가지정 천연기념물로 \n지정, 관리되고 있다.",
    "height": "5.1",
    "openDate": "1952.12.23.",
    "manned": "무",
    "heritage": "제20호",
    "cultural": "",
    "culturalSpace": "",
    "region": "제주단(부산청)"
  },
  {
    "id": 80,
    "category": "힐링",
    "name": "중리항방파제등대",
    "nameEn": "Jungrihang B.Lighthouse",
    "gps": "35.068056, 129.064167",
    "address": "부산광역시 영도구 중리남로 2-15",
    "contact": "051-609-6804 (부산지방해양수산청)",
    "intro": "",
    "desc": "제주 해협과 부산, 목포 등 내륙을 오가는 \n여객선과 화물선 그리고 동중국해를 \n항해하는 선박들의 안전한 밤길을 \n안전하게 인도하고 있다.",
    "height": "14.0",
    "openDate": "2018.08.30.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "부산청"
  },
  {
    "id": 81,
    "category": "힐링",
    "name": "추자도등대",
    "nameEn": "Chujado Lighthouse",
    "gps": "33.955253,  126.2967196",
    "address": "제주특별자치도 제주시 추자면 영흥리 77-3",
    "contact": "064-742-3780 (추자도황로표지관리소)",
    "intro": "",
    "desc": "제주해협과 부산, 목포 등 내륙을 항해하는 \n선박의 안전한 지표로 이용되는 추자도등대는 \n추자군도의 비경을 한눈에 조망할 수 있다.",
    "height": "20.0",
    "openDate": "1980.02.27.",
    "manned": "유",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "제주단(부산청)"
  },
  {
    "id": 82,
    "category": "힐링",
    "name": "통영운하방파제등대",
    "nameEn": "Tongyoungwoonha B.Lighthouse",
    "gps": "34.834250, 128.411000",
    "address": "경남 통영시 미수동 907-1",
    "contact": "055-981-5264(마산지방해양수산청)",
    "intro": "",
    "desc": "빨간 색연필을 형상화한 6각 콘크리트 구조물로 \n통영시에서 등대 디자인을 제안하고\n마산지방해양수산청에서 시공하였다.",
    "height": "7.4",
    "openDate": "2009.09.28.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "마산청"
  },
  {
    "id": 83,
    "category": "힐링",
    "name": "조천읍 북촌리 등명대(도대불)",
    "nameEn": "Bukchon-ri Lighthouse(Dodabbul)",
    "gps": "33.551222, 126.693139",
    "address": "제주 제주시 북촌7길 37",
    "contact": "064-710-6705 (제주세계자연유산센터)",
    "intro": "",
    "desc": "암반이나 암초가 많은 소규모의 포구가 많은 \n제주도에서 현대식 등대가 설치되기 전까지 \n어촌 주민들이 자발적으로 조성하였으며, \n그중 최초로 세워진 등명대로 제주특별자치도 \n등록문화재로 지정되었다.",
    "height": "2.05",
    "openDate": "1915.12.",
    "manned": "",
    "heritage": "",
    "cultural": "○(제주특별자치도 등록문화유산)",
    "culturalSpace": "",
    "region": ""
  },
  {
    "id": 84,
    "category": "일출",
    "name": "거진등대",
    "nameEn": "Geojin Lighthouse",
    "gps": "38.449472, 128.464722",
    "address": "강원특별자치도 고성군 거진읍 등대길 42",
    "contact": "033-520-6275 (동해지방해양수산청)",
    "intro": "거진항을 가장 높은 곳에서 굽어보는",
    "desc": "산책로 따라 걸으며 만나는 동해의 풍경과 해맞이공원에서 맞이하는 일출이 매력적이며, 바다 건너 보이는 백섬과 선박들이 드나드는 거진항의 전경을 감상할 수 있다,",
    "height": "13.0",
    "openDate": "1958.2.27",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "동해청"
  },
  {
    "id": 85,
    "category": "일출",
    "name": "기사문등대",
    "nameEn": "Gisamun Lighthouse",
    "gps": "38.022027, 128.735638",
    "address": "강원특별자치도 양양군 현북면 하광정리 4-1",
    "contact": "033-520-6275 (동해지방해양수산청)",
    "intro": "푸른 소나무 숲과 어우러진 절벽 위에 우뚝 선",
    "desc": "하조대 인근에 위치하여 하조대등대로도 불린다. 200년이 넘은 소나무와 기암절벽이 빚어낸 절경과 동해의 끝없이 펼쳐진 수평선 위로 보이는 일출을 담을 수 있다.",
    "height": "10.0",
    "openDate": "1962.5.20.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "동해청"
  },
  {
    "id": 86,
    "category": "일출",
    "name": "나사방사제등대",
    "nameEn": "Nasa G.Lighthouse",
    "gps": "35.355972, 129.339527",
    "address": "울산광역시 울주군 서생면 나사리 306-29",
    "contact": "052-228-5682 (울산지방해양수산청)",
    "intro": "은빛 모래위에 일출이 피어나는",
    "desc": "푸른 바다를 배경으로 기념사진을 남기기 좋은 나사방사제등대 인근의 나사해수욕장은 북적이는 간절곶을 피해 잠잠하고, 아늑하게 새해를 맞이하기 좋은 울산의 숨은 일출 명소이다.",
    "height": "16.0",
    "openDate": "2013.10.18.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "울산청"
  },
  {
    "id": 87,
    "category": "일출",
    "name": "대송항방파제등대",
    "nameEn": "Daesonghang B.Lighthouse",
    "gps": "35.362778, 129.361306",
    "address": "울산광역시 울주군 서생면 간절곶해안길 222",
    "contact": "052-228-5682 (울산지방해양수산청)",
    "intro": "일출에 마음을 실어 전하는",
    "desc": "‘프로포즈 등대’로 불리는 대송항방파제등대는 사랑하는 이에게 마음을 전하는 특별한 등대로 조성되어 안전한 뱃길을 물론, 사랑의 마음도 안내하는 로맨틱한 등대이다.",
    "height": "9.5",
    "openDate": "2011.8.5.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "울산청"
  },
  {
    "id": 88,
    "category": "일출",
    "name": "대진등대",
    "nameEn": "Daejin Lighthouse",
    "gps": "38.503805, 128.428916",
    "address": "강원특별자치도 고성군 현내면 한나루로4길 16-29",
    "contact": "033-520-6275 (동해지방해양수산청)",
    "intro": "대진항 전역을 비추며 선박을 지켜주는",
    "desc": "대진등대는 동해안 최북단에 위치한 등대로, 등대 앞에서 바라보는 바다의 뛰어난 풍광과 일출, 일몰 사진을 담으려는 사람들이 찾는 명소이다.",
    "height": "31.0",
    "openDate": "1993.4.1.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "동해청"
  },
  {
    "id": 89,
    "category": "일출",
    "name": "대진항남방파제등대",
    "nameEn": "Daejinhang S.B.Lighthouse",
    "gps": "36.558167, 129.434556",
    "address": "경상북도 영덕군 영해면 대진리 220-1",
    "contact": "054-245-1552 (포항지방해양수산청)",
    "intro": "희망의 불빛으로 다시 태어난",
    "desc": "2024년 노후시설을 정비하여 어업 및 관광산업으로 새롭게 도약을 위해 해상 전망대, 해안 산책로 등을 설치하며 영덕 대진항의 명소로 많은 관심을 받고 있다.",
    "height": "9.0",
    "openDate": "2004.12.31.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "포항청"
  },
  {
    "id": 90,
    "category": "일출",
    "name": "대포항동방파제등대",
    "nameEn": "Daepohang E.B.Lighthouse",
    "gps": "38.170055, 128.611666",
    "address": "강원특별자치도 속초시 대포동 952",
    "contact": "033-520-6275 (동해지방해양수산청)",
    "intro": "푸른 바다와 일출의 아름다운 조화",
    "desc": "대포항은 설악산과 함께 속초를 대표하는 관광지로 수산시장에서 즐기는 먹거리는 물론, 대포항 전망대에서 바라보는 일출과 일몰이 아름다워 해맞이 명소로 손꼽힌다.",
    "height": "10.0",
    "openDate": "1968.09.25.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "동해청"
  },
  {
    "id": 91,
    "category": "일출",
    "name": "도동등대",
    "nameEn": "Dodong Lighthouse",
    "gps": "37.487000, 130.919416",
    "address": "경상북도 울릉군 울릉읍 행남길 291-71",
    "contact": "054-791-2594 (도동항로표지관리소)",
    "intro": "울릉도의 관문을 밝히며 항해자를 맞이하는",
    "desc": "울릉도 동쪽 끝에 위치한 도동등대는 등대와 울릉도를 소개하는 전시관과 울릉도의 풍광을 감상할 수 있는 전망대도 갖추고 있으며, 성인봉은 물론, 맑은 날에는 독도까지 눈에 담을 수 있다.",
    "height": "22.0",
    "openDate": "1954.12.19.",
    "manned": "유",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "포항청"
  },
  {
    "id": 92,
    "category": "일출",
    "name": "동암어항방파제등대(빨강)",
    "nameEn": "Dongameohang B.Lighthouse",
    "gps": "35.195027, 129.226944",
    "address": "부산광역시 기장군 기장읍 시랑리 62-19",
    "contact": "051-609-6804 (부산지방해양수산청)",
    "intro": "해안길 끝, 걸음을 멈추게 하는 쉼터",
    "desc": "동암마을에 자리잡은 동암어항은 해동용궁사, 국립수산과학관, 오랑대, 시랑대 등 동부산의 명소들을 두루 만나볼 수 있는 장소로 많은 관광객이 고즈적한 항구의 풍경을 감상하기 위해 방문하고 있다.",
    "height": "12.0",
    "openDate": "2007.11.14.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "부산청"
  },
  {
    "id": 93,
    "category": "일출",
    "name": "묵호등대",
    "nameEn": "Mukho Lighthouse",
    "gps": "37.554472, 129.118555",
    "address": "강원특별자치도 동해시 해맞이길 289",
    "contact": "033-531-3258 (묵호항로표지관리소)",
    "intro": "고즈넉한 등대오름길과 동해의 풍광을 담은",
    "desc": "동해의 안전한 길잡이는 물론, 해양 전망대로써 역할을 훌륭히 수행하고 있는 묵호등대는 황금빛 햇살을 담은 일출과 항구의 불빛들이 선사하는 야경 모두 매력적인 선박과 관광객의 휴식처이다.",
    "height": "24.0",
    "openDate": "1963.6.8.",
    "manned": "유",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "○ (2007.12.)",
    "region": "동해청"
  },
  {
    "id": 94,
    "category": "일출",
    "name": "문중항방파제등대(흰)",
    "nameEn": "Munjunghang B.Lighthouse",
    "gps": "35.304249, 129.261361",
    "address": "부산광역시 기장군 일광읍 문중리 202-5",
    "contact": "051-609-6804 (부산지방해양수산청)",
    "intro": "포구와 바다를 잇는 조용한 안내자",
    "desc": "조용한 어촌의 모습이 인상적인 중동항에 위치한 문중항방파제등대는 인근에 임랑항과 칠암항의 독특한 조형등대들을 함께 만나볼 수 있는데, 화려한 등대들 사이에서 소박한 모습으로 오히려 돋보이는 등대이다.",
    "height": "12.0",
    "openDate": "2002.9.18.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "부산청"
  },
  {
    "id": 95,
    "category": "일출",
    "name": "송대말등대",
    "nameEn": "Songdaemal Lighthouse",
    "gps": "35.807277, 129.511416",
    "address": "경상북도 경주시 감포읍 감포로 226-19",
    "contact": "054-245-1552 (포항지방해양수산청)",
    "intro": "경주 동해 주상절리 위, 푸른 파도와 해돋이를 밝히는",
    "desc": "동해의 기암괴석과 주상절리가 이어지는 절경 위에 위치한 송대말등대는 국보인 감은사지 삼층석탑 모양의 등탑과 빛 체험전시관을 갖춘 명소이며, 경주의 대표적인 해돋이·해넘이 관광지이기도하다.",
    "height": "21.0",
    "openDate": "1955.6.30.",
    "manned": "무",
    "heritage": "제32호",
    "cultural": "",
    "culturalSpace": "",
    "region": "포항청"
  },
  {
    "id": 96,
    "category": "일출",
    "name": "송정항남방파제등대(흰)",
    "nameEn": "Songjeonghang S.B.Lighthouse",
    "gps": "35.180499, 129.207499",
    "address": "부산광역시 해운대구 송정동 288-56",
    "contact": "051-609-6804 (부산지방해양수산청)",
    "intro": "고요한 파도 위로 일출이 스며드는",
    "desc": "부산의 일출 명소인 송정항은 죽도공원과 송일정에서 아름다운 일출을 감상할 수 있어 많은 사람들의 발길이 닿는다. 특히, 송정항에서 보는 등대의 모습이 운치를 더하여 일출 사진 명소로 유명하다.",
    "height": "10.0",
    "openDate": "1999.11.3.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "부산청"
  },
  {
    "id": 97,
    "category": "일출",
    "name": "슬도등대",
    "nameEn": "Seuldo Lighthouse",
    "gps": "35.478127, 129.431038",
    "address": "울산광역시 동구 성끝길 122",
    "contact": "052-228-5682 (울산지방해양수산청)",
    "intro": "파도소리도 예술이 되는 힐링 등대",
    "desc": "섬 전체가 구멍 뚫린 바위로 이루어진 슬도는 이 바위구멍을 드나드는 파도소리가 거문고처럼 들린다 해서 이름 붙여졌다. 방어진 12경 중 하나로 꼽히며, ‘동굴샷’을 찍을 수 있는 사진 명소로도 알려져 있다.",
    "height": "16.0",
    "openDate": "1958.5.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "울산청"
  },
  {
    "id": 98,
    "category": "일출",
    "name": "울릉도등대",
    "nameEn": "Ulleungdo Lighthouse",
    "gps": "37.518027, 130.797638",
    "address": "경북 울릉군 서면 태하등대길 188",
    "contact": "054-245-1552 (포항지방해양수산청)",
    "intro": "푸른 바다 끝 섬을 밝혀주는 희망의 불빛",
    "desc": "등대로 오르는 등산로는 자연적으로 만들어진 오솔길과 푸른 숲으로 되어 있으며, 경사가 완만하고 기암절벽과 풍광이 아름다워 울릉도를 찾는 관광객들의 등산코스로 많은 사랑을 받고 있다.",
    "height": "20.0",
    "openDate": "1958.4.11.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "포항청"
  },
  {
    "id": 99,
    "category": "일출",
    "name": "읍천항남방파제등대",
    "nameEn": "Eupcheonhang S.B.Lighthouse",
    "gps": "35.690250, 129.476278",
    "address": "경상북도 경주시 양남면 읍천리 195-4",
    "contact": "054-245-1552 (포항지방해양수산청)",
    "intro": "낚시꾼과 여행자의 발걸음을 이끄는 바다의 불빛",
    "desc": "등대가 위치한 읍천항은 주상절리와 벽화마을로 유명하며, 파도소리길을 걸으며 만나는 독특한 자연경관과 항구에서 보는 일출이 아름답다.",
    "height": "8.4",
    "openDate": "2001.9.8.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "포항청"
  },
  {
    "id": 100,
    "category": "일출",
    "name": "인구항방파제등대",
    "nameEn": "Inguhang B.Lighthouse",
    "gps": "37.969222, 128.765972",
    "address": "강원특별자치도 양양군 현남면 인구리 1-133",
    "contact": "033-520-6275 (동해지방해양수산청)",
    "intro": "서핑의 명소, 인구항을 지키는 서프보드 등대",
    "desc": "인구항방파제등대가 지키고 있는 인구항 일대는 얕은 수심으로 초보서퍼들도 서핑을 즐기기 좋으며, 끝없이 뻗은 동해를 감상하며 파도타기를 즐길 수 있는 서핑 명소이다.",
    "height": "9.5",
    "openDate": "2003.1.8.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "동해청"
  },
  {
    "id": 101,
    "category": "일출",
    "name": "주전항북방파제등대(빨강)",
    "nameEn": "Jujeonhang N.B.Lighthouse",
    "gps": "35.561306, 129.458306",
    "address": "울산광역시 동구 주전동 94-13",
    "contact": "052-228-5682 (울산지방해양수산청)",
    "intro": "일출의 기운을 담아 선박의 안전을 기원하는 붉은 탑",
    "desc": "삼층석탑을 형상화한 빨간등탑이 인상적인 등대로 선박의 안전 항해를 기원하는 의미를 담고 있다. 등대가 있는 주전항은 몽돌해안과 해안드라이브코스로 유명한데, 고요하고 잔잔한 일출을 보기 좋은 곳이기도 하다.",
    "height": "7.5",
    "openDate": "2007.11.2.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "울산청"
  },
  {
    "id": 102,
    "category": "일출",
    "name": "청사포어항동방파제등대(빨)",
    "nameEn": "Cheongsapoeohang E.B.Lighthouse",
    "gps": "35.159305, 129.1915",
    "address": "부산광역시 해운대구 중동 591-21",
    "contact": "051-609-6804 (부산지방해양수산청)",
    "intro": "아름다운 일출과 노을을 지키는 다정한 쌍둥이",
    "desc": "푸른 바다가 펼쳐진 경관과 부산 제일의 일출과 노을을 감상할 수 청사포다릿돌 전망대 등 다양한 명소가 가득한 청사포어항을 다정하게 지키고 있는 쌍둥이 등대이다.",
    "height": "17.0",
    "openDate": "2008.10.31",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "부산청"
  },
  {
    "id": 103,
    "category": "일출",
    "name": "학리항동방파제등대(흰색)",
    "nameEn": "Hakrihang E.B.Lighthouse",
    "gps": "35.261194, 129.246111",
    "address": "부산 기장군 일광읍 학리 251-22",
    "contact": "051-609-6804 (부산지방해양수산청)",
    "intro": "창공을 가르는 학과 같이 우아하게 학리항을 지키는",
    "desc": "학리항은 기장에서도 오래된 포구로 아기자기한 어촌의 모습을 간직하고 있다. 학리라는 지명은 과거 학들이 많이 서식하여 붙여졌다고 하며, 화려한 야경과 잔잔한 일출을 볼 수 있다.",
    "height": "14.0",
    "openDate": "2014.12.24.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "부산청"
  },
  {
    "id": 104,
    "category": "일출",
    "name": "화암추등대",
    "nameEn": "Hwaamchu Lighthouse",
    "gps": "35.472527, 129.407361",
    "address": "울산광역시 동구 화암등대길 50",
    "contact": "052-228-5682 (울산지방해양수산청)",
    "intro": "꽃바위 마을 끝, 한국에서 가장 높은 등대",
    "desc": "울산항을 드나드는 선박의 안전을 책임지고 있는 화암추 등대는 높이 44m의 한국에서 가장 높은 등대이다. 8층 등대전망대에서는 울산항과 동해바다를 한눈에 담을 수 있다.",
    "height": "44.0",
    "openDate": "1983.1.28.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "울산청"
  },
  {
    "id": 105,
    "category": "일출",
    "name": "후포등대",
    "nameEn": "Hupo Lighthouse",
    "gps": "36.680749, 129.462138",
    "address": "경상북도 울진군 후포면 등기산길 29",
    "contact": "054-245-1552 (포항지방해양수산청)",
    "intro": "등기산 정상에서 청해의 일출",
    "desc": "후포등대가 위치한 등기산은 옛날부터 낮에는 깃발을 꽂고 밤에는 봉화를 피워 선박의 이정표 역할을 했다고 하며, 등대 인근에는 푸른 바다와 일출을 한 눈에 볼 수 있는 전망대가 있어 동해를 누리며 쉬어가기 좋은 등대이다.",
    "height": "11.0",
    "openDate": "1968.1.24.",
    "manned": "무",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": "포항청"
  },
  {
    "id": 106,
    "category": "일출",
    "name": "국립해양박물관",
    "nameEn": "National Maritime Museum of Korea",
    "gps": "35.0785634, 129.082449",
    "address": "부산광역시 영도구 해양로 301번길 45",
    "contact": "051-309-1900(국립해양박물관)",
    "intro": "해양문화의 허브, 바다를 품은 박물관",
    "desc": "국립해양박물관은 해양의 역사와 문화를 탐험할 수 있는 전시실과 실감형 미디어 전시실, 해양생물을 감상 할 수 있는 수족관 등 수준 높은 해양 문화 콘텐츠로 여러분을 바다의 세계로 이끌 것입니다.\n국립해양박물관과 함께 하는 모든 순간이 다양한 즐거움으로 가득하고, 해양의 신비로움에 감탄하며 새로운 경험을 만들어 나갈 수 있기를 기대합니다.",
    "height": "",
    "openDate": "2012.7.09.",
    "manned": "",
    "heritage": "",
    "cultural": "",
    "culturalSpace": "",
    "region": ""
  }
]